server.port=8080

#cegiy92214@inreur.com
#cegiy92214@inreur.comQ
# Database connection properties
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://3.79.94.123:5434/mydb
spring.datasource.username=admin
spring.datasource.password=secretStrashnyiOchen
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


# JPA properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.connection.CharSet=UTF-8
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true

upload.dir = music